#!/bin/bash
echo "Run these commands on the server:"
echo ""
echo "1. Check pg_hba.conf:"
echo "   sudo tail -5 /etc/postgresql/*/main/pg_hba.conf"
echo ""
echo "2. Check if PostgreSQL is listening:"
echo "   sudo netstat -tlnp | grep 5432"
echo ""
echo "3. Check firewall:"
echo "   sudo ufw status | grep 5432"
echo ""
echo "4. Test local connection:"
echo "   PGPASSWORD='GeneVeda2025!Secure' psql -h localhost -U geneveda_user -d geneveda_biosciences -c \"SELECT version();\""
