#!/bin/bash
echo "Run these remaining checks on the server:"
echo ""
echo "2. Check if PostgreSQL is listening:"
echo "   sudo netstat -tlnp | grep 5432"
echo "   (Should show 0.0.0.0:5432, not 127.0.0.1:5432)"
echo ""
echo "3. Check firewall:"
echo "   sudo ufw status | grep 5432"
echo ""
echo "4. If port not allowed, run:"
echo "   sudo ufw allow 5432/tcp"
echo ""
echo "5. Restart PostgreSQL:"
echo "   sudo systemctl restart postgresql"
echo ""
echo "6. Test local connection:"
echo "   PGPASSWORD='GeneVeda2025!Secure' psql -h localhost -U geneveda_user -d geneveda_biosciences -c \"SELECT version();\""
