#!/bin/bash
echo "Run these commands on the server:"
echo ""
echo "1. Check if user exists:"
echo "   sudo -u postgres psql -c \"\\du\""
echo ""
echo "2. Reset password:"
echo "   sudo -u postgres psql -c \"ALTER USER geneveda_user WITH PASSWORD 'GeneVeda2025!Secure';\""
echo ""
echo "3. Grant privileges (if needed):"
echo "   sudo -u postgres psql -d geneveda_biosciences -c \"GRANT ALL ON SCHEMA public TO geneveda_user;\""
echo "   sudo -u postgres psql -d geneveda_biosciences -c \"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO geneveda_user;\""
echo ""
echo "4. Test connection:"
echo "   PGPASSWORD='GeneVeda2025!Secure' psql -h localhost -U geneveda_user -d geneveda_biosciences -c \"SELECT current_database();\""
